### ISSUE TITLE
数据集还有吗？

### ISSUE THREAD

**Issue by shuitai** [LeechanX/Netflix-Recommender-with-Spark#1]
您好，你的百度网盘链接失效了，请问哪里能下到数据集？

**Comment by Michaeljian** [comment]
同问

**Comment by LeechanX** [comment]
netflix电影推荐数据集，百度可以搜到，比如
http://dataju.cn/Dataju/web/datasetInstanceDetail/32

**Comment by Michaeljian** [comment]
十分感谢，之后关于这个项目不懂的地方可以问你吗

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: leechanx <notifications@github.com>
发送时间: Wednesday, June 6, 2018 3:56:49 PM
收件人: LeechanX/Netflix-Recommender-with-Spark
抄送: 周坚; Comment
主题: Re: [LeechanX/Netflix-Recommender-with-Spark] 数据集还有吗？ (#1)


netflix电影推荐数据集，百度可以搜到，比如
http://dataju.cn/Dataju/web/datasetInstanceDetail/32

―
